import type {
  ConceptGenerationResult,
  ConceptProviderContext,
  TurnaroundGenerationResult,
  TurnaroundProviderContext,
  VisualAnalysisResult,
  VisualProviderContext,
} from "./visual-types.js";

export interface VisualProvider {
  readonly providerId: string;
  readonly modelId: string;

  analyze(context: VisualProviderContext): Promise<VisualAnalysisResult>;
  generateConcept(context: ConceptProviderContext): Promise<ConceptGenerationResult>;
  generateTurnaround(context: TurnaroundProviderContext): Promise<TurnaroundGenerationResult>;
}

const TEST_PNG = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Z3QAAAABJRU5ErkJggg==",
  "base64",
);

function requiredDecision(context: ConceptProviderContext) {
  if (context.productKind === "figurine" || context.productKind === "character") {
    return {
      id: "pose",
      prompt: "Confirm the primary figurine/character pose before turnaround generation.",
      required: true,
      status: "open" as const,
    };
  }
  if (
    context.productKind === "vehicle" ||
    context.productKind === "modular_product" ||
    context.productKind === "hybrid"
  ) {
    return {
      id: "module_boundary",
      prompt: "Confirm which major exterior module or body split is authoritative for the visual concept.",
      required: true,
      status: "open" as const,
    };
  }
  return {
    id: "primary_form",
    prompt: "Confirm the primary visual form before turnaround generation.",
    required: true,
    status: "open" as const,
  };
}

export class DeterministicVisualProvider implements VisualProvider {
  readonly providerId = "deterministic-test";
  readonly modelId = "fixture-png-v1";

  async analyze(context: VisualProviderContext): Promise<VisualAnalysisResult> {
    const evidenceAssetIds = context.sourceAssets.map((asset) => asset.assetId);
    const hiddenGeometryLabel =
      context.productKind === "figurine" || context.productKind === "character"
        ? "Back-side anatomy, hair, and clothing surfaces are not fully evidenced by front references."
        : "Rear, underside, and occluded hard-surface geometry are not fully evidenced by the supplied references.";

    return {
      observedFeatures: [
        {
          id: "reference-count",
          type: "reference_count",
          value: context.sourceAssets.length,
          confidence: 1,
          evidenceAssetIds,
        },
        {
          id: "requested-form",
          type: "requested_form",
          value: context.designPrompt,
          confidence: 1,
          evidenceAssetIds,
          userConfirmed: true,
        },
      ],
      assumptions: [
        {
          id: "occluded-geometry",
          statement: hiddenGeometryLabel,
          confidence: 0.35,
          userConfirmed: false,
        },
      ],
      questions: [],
      notes: [
        "Deterministic CI provider: this result proves workflow semantics only and does not perform production vision inference.",
      ],
    };
  }

  async generateConcept(context: ConceptProviderContext): Promise<ConceptGenerationResult> {
    return {
      brief: `${context.productKind}: ${context.designPrompt}`,
      designNotes: [
        `Style: ${context.style ?? "unspecified"}`,
        "Generated by deterministic CI provider; replace provider adapter for production visual quality.",
      ],
      openDecisions: [requiredDecision(context)],
      images: [
        {
          bytes: TEST_PNG,
          mediaType: "image/png",
          widthPx: 1,
          heightPx: 1,
        },
      ],
    };
  }

  async generateTurnaround(
    context: TurnaroundProviderContext,
  ): Promise<TurnaroundGenerationResult> {
    const views =
      context.coveragePolicy === "full_six_view"
        ? ([
            "front",
            "left",
            "right",
            "back",
            "three_quarter_front",
            "three_quarter_back",
          ] as const)
        : (["front", "left", "back", "three_quarter_front"] as const);

    return {
      views: views.map((view) => ({
        view,
        bytes: TEST_PNG,
        mediaType: "image/png" as const,
        widthPx: 1,
        heightPx: 1,
        projection: "orthographic_like" as const,
        notes: "Deterministic CI fixture; not a production-generated visual view.",
      })),
      consistency: {
        pass: true,
        identityScore: 1,
        styleScore: 1,
        silhouetteScore: 1,
        warnings: ["Scores reflect deterministic fixture identity, not model-quality evaluation."],
      },
    };
  }
}
